### PR TITLE
Added stub generation to PHP generator

### PR DESCRIPTION
**Pull request by stanley-cheung**
We are from the gRPC team and would like to add functionality to allow service stub generation for PHP Protobuf

### CODE REVIEW

**Comment by fuhry** [comment]
@stanley-cheung Thanks for this! I will review and test it on Monday.

**Comment by zackangelo** [comment]
@fuhry any update on getting this merged?

**Comment by fuhry** [comment]
@zackangelo Sorry I dropped the ball on this, of course got into work that Monday and was greeted with a whole host of fires to put out from the weekend. Typical SE life :) Will review for you this afternoon.

**Comment by jdpedrie** [comment]
@fuhry Hi Dan. Any chance you've had time to look this over yet?

Thanks!

**Comment by stanley-cheung** [comment]
This became irrelevant now.

**Pull request closed without merging**
